### ISSUE TITLE
Dockerize sante.main

### ISSUE THREAD

**Issue by edgardmarx** [AKSW/sante#14]
This task consists in dockerizing the project sante.main.

- sante.main should have a docker file that pull the project, compile and run sante.main
- the command should reflect the commands in sante.main command line: i.e. docker sante/main -index -endpoint http://../sparql
- the target directory for the index should be fixed to a local directory i.e. $index/

**Comment by ronitblenz** [comment]
In progress,

For test purpose in local environment (using default index to be ```foaf_kg```) I wrote a dockerfile which makes sante (mulang branch) up and running.

For reference : 

```bash
docker run -p7070:7070 ronitblenz/sante
```

Will be working on the separate entities as well.
