### ISSUE TITLE
Dockerize project sante.api

### ISSUE THREAD

**Issue by edgardmarx** [AKSW/sante#15]
This task consists in dockerizing the project sante.api.

- the docker should pull the project sante.api from sante repository and compile it
- the image should run by executing the war inside the image when running it: i.e. docker run sante/api

**Comment by ronitblenz** [comment]
In progress,

For test purpose in local environment (using default index to be ```foaf_kg```) I wrote a dockerfile which makes sante (mulang branch) up and running.

For reference : 

```bash
docker run -p7070:7070 ronitblenz/sante
```

Will be working on the separate entities as well.
